site_name: Screwdriver Guide
site_url: http://screwdriver.cd
repo_url: https://github.com/screwdriver-cd/guide
repo_name: GitHub
site_description: All you need to know about Screwdriver and more
# Due to bug in MKDocs: https://github.com/mkdocs/mkdocs/issues/974
# strict: true
theme_dir: themes/sd
copyright: © 2016 Yahoo! Inc. All rights reserved.
extra_css: [css/homepage.css, css/yaml.css]
extra_javascript: [js/vendor/jquery-3.1.0.min.js, js/yaml.js]

pages:
    - Home: 'index.md'
    - Cluster Management:
        - Configure and Deploy the API: 'cluster-management/configure-api.md'
        - Configure Plugins: 'cluster-management/plugins.md'
        - Overall Architecture: 'cluster-management/overall-architecture.md'
        - Examples:
            - Kubernetes: 'cluster-management/kubernetes.md'
    - Getting Started:
        - Create a Pipeline: 'getting-started/create-pipeline.md'
        - Config File Reference: 'getting-started/yaml.md'
        - Build Secrets: 'getting-started/secrets.md'
    - Internals:
        - API: 'internals/api.md'
        - Execution Engines: 'internals/execution-engines.md'
        - Domain Model: 'internals/domain.md'
    - Community:
        - Contributing: 'community/contributing.md'
        - Support: 'community/support.md'
