workflow:
    - deploy

shared:
    image: python:2

jobs:
  main:
    steps:
      - init: pip install -r requirements.txt
      - validate: markdownlint docs/
      - build: mkdocs build

  deploy:
      steps:
          - init: pip install -r requirements.txt
          - deploy: mkdocs gh-deploy --clean
      secrets:
          # Pushing tags to Git
          - GIT_KEY
